module.exports = {
    copa_clinica: {
        host: '192.168.0.34',
        port: 3050,
        database: 'C:\\Unisoft\\RJ_COPACABANA_CLINICA.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
    copa_contratos: {
        host: '192.168.0.34',
        port: 3050,
        database: 'C:\\Unisoft\\RJ_COPACABANA_CONTRATOS.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
    bota_clinica: {
        host: '192.168.0.181',
        port: 3050,
        database: 'C:\\Unisoft\\BOTAFOGO_CLINICA.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
    bota_contratos: {
        host: '192.168.0.181',
        port: 3050,
        database: 'C:\\Unisoft\\BOTAFOGO_CONTRATOS.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
    tijuca_clinica: {
        host: '192.168.0.146',
        port: 3050,
        database: 'C:\\Unisoft\\Dados\\RJ_TIJUCA_CLINICA.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
    tijuca_contratos: {
        host: '192.168.0.146',
        port: 3050,
        database: 'C:\\Unisoft\\Dados\\RJ_TIJUCA_CONTRATOS.FDB',
        user: 'SYSDBA',
        password: 'masterkey',
        lowercase_keys: false,
        role: null,
        pageSize: 4096,
    },
};